'use client';

import { useQuery } from '@tanstack/react-query';
import { Activity, Database, RefreshCw, Server, Workflow } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { healthService } from '@/services/health';
import { ErrorPanel, StatusPill, TableSkeleton } from '@/features/infrastructure/shared';

export default function SystemPage() {
  const query = useQuery({ queryKey: ['systemHealth'], queryFn: healthService.getSystemHealth, refetchInterval: 30_000 });
  if (query.isPending) return <main className="flex-1 p-4 md:p-6"><TableSkeleton rows={5} /></main>;
  if (query.isError || !query.data) return <main className="flex-1 p-4 md:p-6"><ErrorPanel message="System health could not be loaded." retry={() => query.refetch()} /></main>;
  const system = query.data; const checks = Object.entries(system.checks ?? {}) as [string, string][]; const icons = { database: Database, redis: Server, queue: Workflow };
  return <main className="flex flex-1 flex-col bg-background px-4 py-4 md:px-6 md:py-5"><div className="mx-auto flex w-full max-w-6xl flex-col gap-5"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[.14em] text-primary uppercase">Platform telemetry</p><h1 className="text-xl font-semibold tracking-tight">System</h1><p className="mt-1 text-sm text-muted-foreground">Live connectivity and queue health across the MailPulse control plane.</p></div><Button variant="outline" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw className={query.isFetching ? 'animate-spin' : ''} />Refresh</Button></header><Card className="border-border/80"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary"><Activity /></div><div className="min-w-0 flex-1"><p className="font-medium">{system.service} <span className="font-mono text-xs text-muted-foreground">v{system.version}</span></p><p className="text-sm text-muted-foreground">{system.environment} environment · updates every 30 seconds</p></div><StatusPill status={system.status} /></CardContent></Card><section className="grid gap-4 md:grid-cols-3">{checks.map(([name, state]) => { const Icon = icons[name as keyof typeof icons] ?? Server; return <Card key={name}><CardHeader className="flex-row items-center gap-3 space-y-0 pb-3"><span className="rounded-md bg-muted p-2"><Icon className="size-4" /></span><div><CardTitle className="text-sm capitalize">{name}</CardTitle><CardDescription>Connectivity check</CardDescription></div></CardHeader><CardContent><StatusPill status={state === 'connected' || state === 'ok' ? 'healthy' : 'error'} /><p className="mt-2 break-words font-mono text-xs text-muted-foreground">{state}</p></CardContent></Card>; })}</section><Card><CardHeader><CardTitle className="text-sm">Webhook delivery queue</CardTitle><CardDescription>Current delivery backlog, as reported by the system health endpoint.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{Object.entries(system.deliveries ?? {}).map(([label, value]) => <div className="rounded-md border bg-muted/20 p-4" key={label}><p className="text-xs text-muted-foreground capitalize">{label.replace('_', ' ')}</p><p className="mt-1 font-mono text-2xl font-semibold">{String(value)}</p></div>)}</CardContent></Card></div></main>;
}
