import type {Metadata} from "next";
import {Toaster} from "@/components/ui/toast"
import QueryProvider from "../components/QueryProvider";
import {Geist, Geist_Mono, Inter, Urbanist} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
});
export const metadata: Metadata = {
    title: "MailPulse",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <QueryProvider>
            <html
                lang="en"
                className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${urbanist.variable} h-full antialiased`}
            >
            <body className="min-h-full flex flex-col">
            {children}
            <Toaster/>
            </body>
            </html>
        </QueryProvider>
    );
}
