'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Copy, KeyRound, Loader2, Plus, Send, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Field, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { infrastructureService } from '@/services/infrastructure';
import type { WebhookInput } from '@/services/Types';
import { toast } from '@/components/ui/toast';
import { EmptyPanel, ErrorPanel, formatDate, StatusPill, TableSkeleton } from '@/features/infrastructure/shared';

const initial: WebhookInput = { url: '', name: '', event_types: ['email.received'], is_enabled: true };
export default function WebhooksPage() {
  const client = useQueryClient(); const [adding, setAdding] = useState(false); const [form, setForm] = useState(initial); const [secret, setSecret] = useState<string | null>(null); const [selected, setSelected] = useState<string | null>(null); const [deliveryOffset, setDeliveryOffset] = useState(0); const limit = 10;
  const query = useQuery({ queryKey: ['webhooks'], queryFn: infrastructureService.listWebhooks });
  const deliveries = useQuery({ queryKey: ['webhookDeliveries', selected, deliveryOffset], queryFn: () => infrastructureService.listDeliveries(selected!, limit, deliveryOffset), enabled: Boolean(selected) });
  const invalidate = () => client.invalidateQueries({ queryKey: ['webhooks'] });
  const create = useMutation({ mutationFn: infrastructureService.createWebhook, onSuccess: (data) => { invalidate(); setSecret(data.secret); setAdding(false); setForm(initial); toast.add({ title: 'Webhook created', description: 'Copy the signing secret now; it will not be shown again.', type: 'success' }); }, onError: (error) => toast.add({ title: 'Webhook creation failed', description: error.message, type: 'error' }) });
  const update = useMutation({ mutationFn: ({ id, is_enabled }: { id: string; is_enabled: boolean }) => infrastructureService.updateWebhook(id, { is_enabled }), onSuccess: invalidate, onError: (error) => toast.add({ title: 'Webhook update failed', description: error.message, type: 'error' }) });
  const remove = useMutation({ mutationFn: infrastructureService.deleteWebhook, onSuccess: () => { invalidate(); toast.add({ title: 'Webhook removed', type: 'success' }); }, onError: (error) => toast.add({ title: 'Webhook removal failed', description: error.message, type: 'error' }) });
  const test = useMutation({ mutationFn: infrastructureService.testWebhook, onSuccess: (data) => toast.add({ title: data.success ? `Test delivered (${data.http_status_code})` : `Test failed (${data.http_status_code})`, description: data.response_body || undefined, type: data.success ? 'success' : 'error' }), onError: (error) => toast.add({ title: 'Webhook test failed', description: error.message, type: 'error' }) });
  const rotate = useMutation({ mutationFn: infrastructureService.rotateWebhookSecret, onSuccess: (data) => { setSecret(data.secret); invalidate(); toast.add({ title: 'Signing secret rotated', description: 'Copy the new value now.', type: 'success' }); }, onError: (error) => toast.add({ title: 'Secret rotation failed', description: error.message, type: 'error' }) });
  const copy = async () => { if (!secret) return; await navigator.clipboard.writeText(secret); toast.add({ title: 'Secret copied', type: 'success' }); };
  return <main className="flex flex-1 flex-col bg-background px-4 py-4 md:px-6 md:py-5"><div className="mx-auto flex w-full max-w-7xl flex-col gap-5"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[.14em] text-primary uppercase">Outbound delivery</p><h1 className="text-xl font-semibold tracking-tight">Webhooks</h1><p className="mt-1 text-sm text-muted-foreground">Signed event destinations and their delivery history.</p></div><Button onClick={() => setAdding((value) => !value)}><Plus />{adding ? 'Close setup' : 'Add webhook'}</Button></header>
  {secret && <div className="flex flex-col gap-3 rounded-lg border border-amber-500/40 bg-amber-500/10 p-4 sm:flex-row sm:items-center"><KeyRound className="size-5 shrink-0 text-amber-700 dark:text-amber-400" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">Store this signing secret securely</p><p className="truncate font-mono text-xs text-muted-foreground">{secret}</p></div><Button size="sm" variant="outline" onClick={copy}><Copy />Copy secret</Button><Button size="sm" variant="ghost" onClick={() => setSecret(null)}>Dismiss</Button></div>}
  {adding && <Card><CardContent className="p-4"><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-4" onSubmit={(event) => { event.preventDefault(); create.mutate({ ...form, name: form.name || null }); }}><FormField label="Endpoint URL"><Input required type="url" placeholder="https://app.example.com/hooks" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} /></FormField><FormField label="Name (optional)"><Input value={form.name ?? ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /></FormField><FormField label="Event types"><Input required value={form.event_types.join(', ')} onChange={(e) => setForm({ ...form, event_types: e.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></FormField><label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" checked={form.is_enabled} onChange={(e) => setForm({ ...form, is_enabled: e.target.checked })} /> Enable delivery</label><div className="md:col-span-2 xl:col-span-4"><Button disabled={create.isPending} type="submit">{create.isPending && <Loader2 className="animate-spin" />}Create webhook</Button></div></form></CardContent></Card>}
  {query.isPending ? <TableSkeleton /> : query.isError ? <ErrorPanel message="Webhook configuration could not be loaded." retry={() => query.refetch()} /> : !query.data?.length ? <EmptyPanel title="No webhook destinations" detail="Create a signed endpoint to deliver processed email events to your application." /> : <div className="overflow-hidden rounded-lg border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="border-b bg-muted/30 text-xs tracking-wide text-muted-foreground uppercase"><tr><th className="px-4 py-3 font-medium">Destination</th><th className="px-4 py-3 font-medium">Events</th><th className="px-4 py-3 font-medium">Secret</th><th className="px-4 py-3 font-medium">Updated</th><th className="px-4 py-3 text-right font-medium">Controls</th></tr></thead><tbody>{query.data.map((webhook) => <tr className="border-b border-border/70 last:border-0" key={webhook.id}><td className="px-4 py-3"><p className="font-medium">{webhook.name || new URL(webhook.url).hostname}</p><p className="max-w-80 truncate font-mono text-xs text-muted-foreground">{webhook.url}</p></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{webhook.event_types.map((type) => <span className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs" key={type}>{type}</span>)}</div></td><td className="px-4 py-3"><p className="font-mono text-xs">{webhook.secret_prefix}</p><StatusPill status={webhook.is_enabled ? 'enabled' : 'disabled'} /></td><td className="px-4 py-3 text-xs text-muted-foreground">{formatDate(webhook.updated_at)}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button size="sm" variant="outline" onClick={() => { setSelected(webhook.id); setDeliveryOffset(0); }}>History</Button><Button size="icon-sm" variant="outline" aria-label="Test webhook" disabled={test.isPending} onClick={() => test.mutate(webhook.id)}><Send /></Button><Button size="icon-sm" variant="outline" aria-label="Rotate secret" disabled={rotate.isPending} onClick={() => rotate.mutate(webhook.id)}><KeyRound /></Button><Button size="sm" variant="outline" disabled={update.isPending} onClick={() => update.mutate({ id: webhook.id, is_enabled: !webhook.is_enabled })}>{webhook.is_enabled ? 'Pause' : 'Enable'}</Button><Button size="icon-sm" variant="destructive" aria-label="Remove webhook" disabled={remove.isPending} onClick={() => remove.mutate(webhook.id)}><Trash2 /></Button></div></td></tr>)}</tbody></table></div></div>}
  {selected && <DeliveryHistory data={deliveries.data} error={deliveries.isError} loading={deliveries.isPending} offset={deliveryOffset} onClose={() => setSelected(null)} onNext={() => setDeliveryOffset((value) => value + limit)} onPrevious={() => setDeliveryOffset((value) => Math.max(0, value - limit))} />}</div></main>;
}
function DeliveryHistory({ data, loading, error, offset, onClose, onPrevious, onNext }: { data: Awaited<ReturnType<typeof infrastructureService.listDeliveries>> | undefined; loading: boolean; error: boolean; offset: number; onClose: () => void; onPrevious: () => void; onNext: () => void }) { return <Card><CardContent className="p-4"><div className="mb-3 flex items-center justify-between"><div><p className="font-medium">Delivery history</p><p className="text-xs text-muted-foreground">Most recent attempts for this destination.</p></div><Button size="sm" variant="ghost" onClick={onClose}>Close</Button></div>{loading ? <TableSkeleton rows={3} /> : error ? <ErrorPanel message="Delivery history could not be loaded." /> : !data?.items.length ? <EmptyPanel title="No deliveries yet" detail="Delivery attempts will appear here after matching events are processed." /> : <><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="text-left text-xs text-muted-foreground"><tr><th className="pb-2">Status</th><th className="pb-2">HTTP</th><th className="pb-2">Attempts</th><th className="pb-2">Delivered</th><th className="pb-2">Last error</th></tr></thead><tbody>{data.items.map((item) => <tr className="border-t border-border/70" key={item.id}><td className="py-2"><StatusPill status={item.status} /></td><td className="py-2 font-mono text-xs">{item.http_status_code ?? '—'}</td><td className="py-2">{item.attempt_count}</td><td className="py-2 text-xs text-muted-foreground">{formatDate(item.delivered_at)}</td><td className="max-w-64 truncate py-2 text-xs text-destructive" title={item.last_error ?? undefined}>{item.last_error ?? '—'}</td></tr>)}</tbody></table></div><div className="mt-3 flex justify-end gap-2"><Button size="sm" variant="outline" disabled={offset === 0} onClick={onPrevious}>Previous</Button><Button size="sm" variant="outline" disabled={data.items.length < data.limit} onClick={onNext}>Next</Button></div></>}</CardContent></Card> }
function FormField({ label, children }: { label: string; children: React.ReactNode }) { return <Field><FieldLabel>{label}</FieldLabel>{children}</Field>; }
