#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# MailPulse — environment generator
#
# Fills in every value that can be derived or safely auto-generated for local
# development and Docker Compose, leaving only genuinely secret/external
# values (mailbox credentials, webhook URLs, production secrets) for you.
#
# Behaviour:
#   • Idempotent — NEVER overwrites an existing non-empty value.
#   • Generates backend  → .env            (api + worker read this via compose)
#   • Generates frontend → frontend/.env.local
#   • Writes files only when this script runs OUTSIDE a container
#     (env_file mounts into the container make writes pointless + harmful).
#
# Usage:
#   scripts/generate-env.sh            # container networking (default)
#   scripts/generate-env.sh --host     # localhost URLs (bare `uvicorn` dev)
#
# In compose, this runs as a one-shot service bound to the repo mount:
#   docker compose run --rm env-gen     # then docker compose up
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

MODE="${1:-container}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Allow overriding the target root (tests, compose mounts repo at /app so the
# default is correct there; `--root DIR` is for running against a copy).
if [[ "${2:-}" == "--root" && -n "${3:-}" ]]; then
  ROOT="$3"
fi

BACKEND_ENV="$ROOT/.env"
FRONTEND_ENV="$ROOT/frontend/.env.local"

# ── Postgres/Redis defaults (mirror docker-compose.yml) ─────────────────────
PG_USER="${POSTGRES_USER:-mailpulse}"
PG_PASS="${POSTGRES_PASSWORD:-mailpulse}"
PG_DB="${POSTGRES_DB:-mailpulse}"

if [[ "$MODE" == "--host" ]]; then
  # Bare-metal dev: services reachable on localhost (compose publishes 5433/6379)
  DB_HOST="localhost:5433"
  REDIS_HOST="localhost:6379"
else
  # In compose: service names resolve on the shared network
  DB_HOST="postgres:5432"
  REDIS_HOST="redis:6379"
fi

DATABASE_URL="postgresql+asyncpg://${PG_USER}:${PG_PASS}@${DB_HOST}/${PG_DB}"
REDIS_URL="redis://${REDIS_HOST}/0"

# ── Random value generators (pure bash — /dev/urandom, no Python dep) ───────
# $1 = length in bytes; output is URL-safe base64 (≈ 1.33× the byte length)
gen_secret() {
  head -c "$1" /dev/urandom | base64 | tr '+/' '-_' | tr -d '='
}
# $1 = length in bytes; output is lowercase hex (2× the byte length)
gen_hex() {
  head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
}

# ── Key/value file writer (idempotent) ──────────────────────────────────────
# usage: write_kv <file> <KEY> <value>
# Appends `KEY=value` only if KEY is absent OR empty in the target file.
write_kv() {
  local file="$1" key="$2" value="$3"
  mkdir -p "$(dirname "$file")"
  touch "$file"

  if grep -qE "^${key}=" "$file"; then
    # Key exists — check the value isn't empty/placeholder before leaving it.
    local current
    current="$(grep -E "^${key}=" "$file" | head -1 | cut -d= -f2-)"
    case "$current" in
      ""|"change-me"*|"changeme"*) ;; # fall through and replace
      *) return 0 ;;                  # real value present — keep it
    esac
    # Replace in place (value may contain '/' so use | as delimiter)
    if [[ "$(uname -s)" == "Darwin" ]]; then
      sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
    else
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    fi
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

write_header() {  # $1 = file, $2 = title
  local file="$1" title="$2"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  if ! grep -qF "# Auto-generated by scripts/generate-env.sh" "$file" 2>/dev/null; then
    printf '# %s — generated %s\n' "$title" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$file"
    printf '# Auto-generated by scripts/generate-env.sh — safe to re-run (never clobbers real secrets)\n' >> "$file"
  fi
}

# ── Skip when running inside a runtime container ────────────────────────────
# The repo bind-mount is host-backed, so files written here ARE visible to
# the host. env-gen (docker-compose.yml) sets ENV_GEN_ALLOWED=1 to say
# "writes are meaningful" — any other in-container run (e.g. a stray call
# from api/worker) should exit early instead of writing to an ephemeral FS.
if [[ -f "/.dockerenv" && "${ENV_GEN_ALLOWED:-0}" != "1" ]]; then
  echo "[generate-env] inside a container with no host mount — nothing to do."
  exit 0
fi

echo "[generate-env] mode: $MODE"
echo "[generate-env] backend: $BACKEND_ENV"
echo "[generate-env] frontend: $FRONTEND_ENV"

# ── Backend .env ────────────────────────────────────────────────────────────
write_header "$BACKEND_ENV" "MailPulse backend"

write_kv "$BACKEND_ENV" "APP_NAME"        "MailPulse"
write_kv "$BACKEND_ENV" "APP_VERSION"     "0.1.0"
write_kv "$BACKEND_ENV" "ENVIRONMENT"     "development"
write_kv "$BACKEND_ENV" "DEBUG"           "false"

write_kv "$BACKEND_ENV" "DATABASE_URL"    "$DATABASE_URL"
write_kv "$BACKEND_ENV" "REDIS_URL"       "$REDIS_URL"

# Secrets — generated only when missing or placeholder.
write_kv "$BACKEND_ENV" "JWT_SECRET_KEY"  "$(gen_secret 48)"
write_kv "$BACKEND_ENV" "CRON_SECRET_KEY" "$(gen_hex 32)"
write_kv "$BACKEND_ENV" "CREDENTIAL_ENCRYPTION_KEY" "$(gen_secret 32)"

write_kv "$BACKEND_ENV" "JWT_ALGORITHM"           "HS256"
write_kv "$BACKEND_ENV" "ACCESS_TOKEN_EXPIRE_MINUTES" "30"
write_kv "$BACKEND_ENV" "REFRESH_TOKEN_EXPIRE_DAYS"   "7"

write_kv "$BACKEND_ENV" "EMAIL_MONITOR_POLL_INTERVAL_SECONDS" "60"
write_kv "$BACKEND_ENV" "ARQ_MAX_TRIES"   "4"
write_kv "$BACKEND_ENV" "ARQ_JOB_TIMEOUT" "300"
write_kv "$BACKEND_ENV" "WEBHOOK_MAX_ATTEMPTS" "4"

# ── Frontend .env.local ─────────────────────────────────────────────────────
write_header "$FRONTEND_ENV" "MailPulse dashboard (Next.js)"

write_kv "$FRONTEND_ENV" "NEXT_PUBLIC_API_URL"            "http://localhost:3000"
if [[ "$MODE" == "--host" ]]; then
  write_kv "$FRONTEND_ENV" "NEXT_PUBLIC_FASTAPI_BACKEND_URL" "http://localhost:8080"
else
  write_kv "$FRONTEND_ENV" "NEXT_PUBLIC_FASTAPI_BACKEND_URL" "http://api:8080"
fi

echo "[generate-env] done."
echo
echo "  Backend : $BACKEND_ENV"
echo "  Frontend: $FRONTEND_ENV"
echo
echo "Next step:  docker compose up --build"
echo "Or for bare-metal dev (uvicorn + next dev):  scripts/generate-env.sh --host"